name: Check Environments

on:
  pull_request:

permissions:
  contents: read

jobs:
  check-environments:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.3

      - name: Load env
        id: load-env
        uses: ./.github/actions/load-env

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ steps.load-env.outputs.hugo-version }}
          extended: true

      - name: Check environments
        run: ./check-environments.sh
